function generatePDFReport(scenario, email) {
  return `
    <html>
      <head>
        <style>
          body { font-family: Arial, sans-serif; margin: 20px; }
          h2 { color: #2E86C1; }
          pre { background: #F4F6F7; padding: 10px; }
          hr { margin-top: 30px; }
        </style>
      </head>
      <body>
        <h2>ROI Simulation Report - ${scenario.scenario_name}</h2>
        <p><b>Email:</b> ${email}</p>
        <h3>Inputs:</h3>
        <pre>${JSON.stringify(scenario.input, null, 2)}</pre>
        <h3>Results:</h3>
        <pre>${JSON.stringify(scenario.results, null, 2)}</pre>
        <hr>
        <small>Generated by Invoicing ROI Simulator</small>
      </body>
    </html>
  `;
}

module.exports = { generatePDFReport };
